# Signup
### should can create new user
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "username": "test",
  "full_name": "test",
  "password": "test",
  "confirm_password": "test",
  "gender": "male"
}

### should reject if username already exist
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "username": "test",
  "full_name": "test",
  "password": "test",
  "confirm_password": "test",
  "gender": "male"
}

### should reject if passwords don't match
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "username": "test",
  "full_name": "test",
  "password": "test",
  "confirm_password": "testt",
  "gender": "male"
}

### should reject if request is invalid
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "username": "test123",
  "full_name": "test",
  "password": "test",
  "confirm_password": "test"
}


# Login
### should can login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

### should reject if password is wrong
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test123"
}

### should reject if username is not found
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "test123",
  "password": "test"
}

### should reject if request is invalid
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "test"
}

# Logout
### should can logout
POST http://localhost:5000/api/auth/logout